# Generated by Django 6.0.5 on 2026-05-20 15:00

import apps.subscribers.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7, validators=[apps.subscribers.models._validate_hex_color])),
                ('auto_rule', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('sync', 'Sync'), ('signup_form', 'Signup Form')], default='manual', max_length=20)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('health_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('double_optin_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('double_optin_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='subscribers.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'health_score'], name='sub_status_health'), models.Index(fields=['source', 'source_id'], name='sub_source_sourceid')],
            },
        ),
    ]
