# Generated by Django 6.0.5 on 2026-05-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consent', '0003_alter_consentrecord_email_type_and_more'),
        ('subscribers', '0001_initial'),
        ('templates_mgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('subject_line', models.CharField(max_length=255, verbose_name='subject line')),
                ('audience_filter', models.JSONField(blank=True, default=dict, help_text='JSON filter criteria for selecting recipients.', verbose_name='audience filter')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='recipient count')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='consent.emailtype', verbose_name='email type')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='templates_mgr.emailtemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_line_used', models.CharField(max_length=255, verbose_name='subject line used')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='provider message ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed')], default='queued', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('bounced_at', models.DateTimeField(blank=True, null=True, verbose_name='bounced at')),
                ('complained_at', models.DateTimeField(blank=True, null=True, verbose_name='complained at')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_sends', to='campaigns.campaign', verbose_name='campaign')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_sends', to='consent.emailtype', verbose_name='email type')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_sends', to='subscribers.subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'email send',
                'verbose_name_plural': 'email sends',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaign_status'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-scheduled_at'], name='campaign_scheduled'),
        ),
        migrations.AddIndex(
            model_name='emailsend',
            index=models.Index(fields=['subscriber', '-sent_at'], name='emailsend_sub_sent'),
        ),
        migrations.AddIndex(
            model_name='emailsend',
            index=models.Index(fields=['campaign'], name='emailsend_campaign'),
        ),
        migrations.AddIndex(
            model_name='emailsend',
            index=models.Index(fields=['provider_message_id'], name='emailsend_provider_id'),
        ),
    ]
