# Generated by Django 6.0.5 on 2026-05-21 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('consent', '0003_alter_consentrecord_email_type_and_more'),
        ('subscribers', '0001_initial'),
        ('templates_mgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('trigger_type', models.CharField(choices=[('subscriber_created', 'Subscriber Created'), ('tag_added', 'Tag Added'), ('manual', 'Manual')], max_length=30, verbose_name='trigger type')),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Trigger matching rules, e.g. {"tags": ["pro"], "source": "signup_form"}.', verbose_name='trigger config')),
            ],
            options={
                'verbose_name': 'sequence',
                'verbose_name_plural': 'sequences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('delay_hours', models.PositiveIntegerField(default=0, help_text='Hours to wait after enrollment before sending this step.', verbose_name='delay hours')),
                ('subject_override', models.CharField(blank=True, default='', help_text="Leave blank to use the template's default subject.", max_length=255, verbose_name='subject override')),
                ('condition', models.JSONField(blank=True, help_text='Optional JSON filter to evaluate before sending, e.g. {"health_below": 30}.', null=True, verbose_name='condition')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_steps', to='consent.emailtype', verbose_name='email type')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='campaigns.sequence', verbose_name='sequence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_steps', to='templates_mgr.emailtemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'sequence step',
                'verbose_name_plural': 'sequence steps',
                'ordering': ['order'],
                'unique_together': {('sequence', 'order')},
            },
        ),
        migrations.AddField(
            model_name='emailsend',
            name='sequence_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_sends', to='campaigns.sequencestep', verbose_name='sequence step'),
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='enrolled at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campaigns.sequence', verbose_name='sequence')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='subscribers.subscriber', verbose_name='subscriber')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_enrollments', to='campaigns.sequencestep', verbose_name='current step')),
            ],
            options={
                'verbose_name': 'sequence enrollment',
                'verbose_name_plural': 'sequence enrollments',
                'indexes': [models.Index(fields=['status'], name='seqenrollment_status')],
                'unique_together': {('subscriber', 'sequence')},
            },
        ),
    ]
