# Generated by Django 6.0.5 on 2026-05-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable template name.', max_length=200, verbose_name='name')),
                ('slug', models.SlugField(help_text='Stable identifier used by campaigns and sequences.', unique=True, verbose_name='slug')),
                ('subject_default', models.CharField(help_text='Subject line, may contain {{ variable }} placeholders.', max_length=255, verbose_name='default subject')),
                ('html_body', models.TextField(help_text='Email body content rendered inside the base layout.', verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, default='', help_text='Optional plain-text version. Left blank, HTML is sent only.', verbose_name='plain text body')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['name'],
            },
        ),
    ]
