# Generated by Django 6.0.5 on 2026-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='provider')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_type', '-created_at'], name='webhook_prov_type_created')],
            },
        ),
    ]
