# Generated by Django 6.0.5 on 2026-05-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant', 'Grant'), ('withdraw', 'Withdraw')], max_length=10, verbose_name='action')),
                ('method', models.CharField(max_length=100, verbose_name='method')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('proof', models.TextField(blank=True, verbose_name='proof')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consent.emailtype', verbose_name='email type')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='subscribers.subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'consent record',
                'verbose_name_plural': 'consent records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscriber', 'email_type', '-created_at'], name='consent_sub_type_created')],
            },
        ),
        migrations.CreateModel(
            name='UnsubscribeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('method', models.CharField(max_length=100, verbose_name='method')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consent.emailtype', verbose_name='email type')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsubscribe_events', to='subscribers.subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'unsubscribe event',
                'verbose_name_plural': 'unsubscribe events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='unsub_email'), models.Index(fields=['subscriber'], name='unsub_subscriber')],
            },
        ),
    ]
