# Generated by Django 6.0.5 on 2026-05-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_consentrecord_unsubscribeevent'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='email_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='consent.emailtype', verbose_name='email type'),
        ),
        migrations.AlterField(
            model_name='unsubscribeevent',
            name='email_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='consent.emailtype', verbose_name='email type'),
        ),
        migrations.AlterField(
            model_name='unsubscribeevent',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsubscribe_events', to='subscribers.subscriber', verbose_name='subscriber'),
        ),
    ]
